name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '11,37 12,15,18,21,23 * * 1,2,3,4,5,6'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install packages
      run: |-
        pip install pandas
        pip install alphaVantage-api
        pip install python-dateutil
    - name: Get stock prices
      run: |-
        python src/get-and-transform-data.py --key ${{ secrets.ALPHAVANTAGE_KEY }}
      shell: sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
